<?php

/**
 * @file
 *  Link webform functionalities to services module.
 */

/**
 * Implementation of hook_perm().
 */
function webform_service_perm() {
  return array(
    'access all webform results',
  );
}

/**
 * Implementation of hook_service().
 */
function webform_service_service() {
  return array(

    // webform.list
    array(
      '#method'           => 'webform.list',
      '#callback'         => 'webform_service_list',
      '#access callback'  => 'webform_service_list_access',
      '#file'             => array('file' => 'inc', 'module' => 'webform_service'),
      '#args'             => array(),
      '#return'           => 'struct',
      '#help'             => t('Returns a list of webform nids')),

    // webform.get
    array(
      '#method'           => 'webform.get',
      '#callback'         => 'webform_service_get',
      '#access callback'  => 'webform_service_get_access',
      '#file'             => array('file' => 'inc', 'module' => 'webform_service'),
      '#args'             => array(
        array(
          '#name'           => 'nid',
          '#type'           => 'int',
          '#description'    => t('The nid of the webform')),
        array(
          '#name'           => 'fromdate',
          '#type'           => 'int',
          '#description'    => t('Submissions created after this date.')),
      ),
      '#return'           => 'struct',
      '#help'             => t('Returns a list of sids')),
    
    // webform.view
    array(
      '#method'           => 'webform.view',
      '#callback'         => 'webform_service_view',
      '#access callback'  => 'webform_service_view_access',
      '#file'             => array('file' => 'inc', 'module' => 'webform_service'),
      '#args'             => array(
        array(
          '#name'         => 'nid',
          '#type'         => 'int',
          '#description'  => t('The nid of the webform.')),
        array(
          '#name'         => 'sid',
          '#type'         => 'int',
          '#description'  => t('A submission id.')),
      ),
      '#return'           => 'struct',
      '#help'             => t('Returns submission data.')),
    
    // webform.save
    /*
    array(
      '#method'           => 'webform.save',
      '#callback'         => 'webform_service_save',
      '#access callback'  => 'webform_service_save_access',
      '#file'             => array('file' => 'inc', 'module' => 'webform_service'),
      '#args'             => array(
        array(
          '#name'           => 'submission',
          '#type'           => 'array',
          '#description'    => t('A node object. Upon creation, node object must include "type". Upon update, node object must include "nid" and "changed".')),
      ),
      '#return'           => 'struct',
      '#help'             => t('Save a webform submission object.')),

    // webform.delete
    array(
      '#method'           => 'webform.delete',
      '#callback'         => 'webform_service_delete',
      '#access callback'  => 'webform_service_delete_access',
      '#file'             => array('file' => 'inc', 'module' => 'webform_service'),
      '#args'             => array(
        array(
          '#name'           => 'sid',
          '#type'           => 'int',
          '#description'    => t('A submission id.'))),
      '#help'             => t('Delete a submission.')),
      */
  );
}